services:
  flask_app:
    build: .

    container_name: flaskv1

    ports:
      - "2423:2423"

    expose:
      - "2423"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

    container_name: nginxv1

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - flask_app
